// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file Base.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace { char dummy; }
#endif

#include "Base.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>

using namespace eprosima::fastcdr::exception;

#include <utility>

mPoint::mPoint() {
    m_id = 0;

    m_x = 0.0;

    m_y = 0.0;

    m_z = 0.0;


}

mPoint::~mPoint() {
}

mPoint::mPoint(const mPoint &x) {
    m_id = x.m_id;
    m_x = x.m_x;
    m_y = x.m_y;
    m_z = x.m_z;
}

mPoint::mPoint(mPoint &&x) {
    m_id = x.m_id;
    m_x = x.m_x;
    m_y = x.m_y;
    m_z = x.m_z;
}

mPoint &mPoint::operator=(const mPoint &x) {
    m_id = x.m_id;
    m_x = x.m_x;
    m_y = x.m_y;
    m_z = x.m_z;

    return *this;
}

mPoint &mPoint::operator=(mPoint &&x) {
    m_id = x.m_id;
    m_x = x.m_x;
    m_y = x.m_y;
    m_z = x.m_z;

    return *this;
}

size_t mPoint::getMaxCdrSerializedSize(size_t current_alignment) {
    size_t initial_alignment = current_alignment;

    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    return current_alignment - initial_alignment;
}

size_t mPoint::getCdrSerializedSize(const mPoint &data, size_t current_alignment) {
    (void) data;
    size_t initial_alignment = current_alignment;

    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    current_alignment += 8 + eprosima::fastcdr::Cdr::alignment(current_alignment, 8);


    return current_alignment - initial_alignment;
}

void mPoint::serialize(eprosima::fastcdr::Cdr &scdr) const {
    scdr << m_id;
    scdr << m_x;
    scdr << m_y;
    scdr << m_z;
}

void mPoint::deserialize(eprosima::fastcdr::Cdr &dcdr) {
    dcdr >> m_id;
    dcdr >> m_x;
    dcdr >> m_y;
    dcdr >> m_z;
}

size_t mPoint::getKeyMaxCdrSerializedSize(size_t current_alignment) {
    size_t current_align = current_alignment;


    return current_align;
}

bool mPoint::isKeyDefined() {
    return false;
}

void mPoint::serializeKey(eprosima::fastcdr::Cdr &scdr) const {
    (void) scdr;


}

mLine::mLine() {
    m_id = 0;


}

mLine::~mLine() {
}

mLine::mLine(const mLine &x) {
    m_id = x.m_id;
    m_p1 = x.m_p1;
    m_p2 = x.m_p2;
}

mLine::mLine(mLine &&x) {
    m_id = x.m_id;
    m_p1 = std::move(x.m_p1);
    m_p2 = std::move(x.m_p2);
}

mLine &mLine::operator=(const mLine &x) {
    m_id = x.m_id;
    m_p1 = x.m_p1;
    m_p2 = x.m_p2;

    return *this;
}

mLine &mLine::operator=(mLine &&x) {
    m_id = x.m_id;
    m_p1 = std::move(x.m_p1);
    m_p2 = std::move(x.m_p2);

    return *this;
}

size_t mLine::getMaxCdrSerializedSize(size_t current_alignment) {
    size_t initial_alignment = current_alignment;

    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    current_alignment += mPoint::getMaxCdrSerializedSize(current_alignment);
    current_alignment += mPoint::getMaxCdrSerializedSize(current_alignment);

    return current_alignment - initial_alignment;
}

size_t mLine::getCdrSerializedSize(const mLine &data, size_t current_alignment) {
    (void) data;
    size_t initial_alignment = current_alignment;

    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    current_alignment += mPoint::getCdrSerializedSize(data.p1(), current_alignment);
    current_alignment += mPoint::getCdrSerializedSize(data.p2(), current_alignment);

    return current_alignment - initial_alignment;
}

void mLine::serialize(eprosima::fastcdr::Cdr &scdr) const {
    scdr << m_id;
    scdr << m_p1;
    scdr << m_p2;
}

void mLine::deserialize(eprosima::fastcdr::Cdr &dcdr) {
    dcdr >> m_id;
    dcdr >> m_p1;
    dcdr >> m_p2;
}

size_t mLine::getKeyMaxCdrSerializedSize(size_t current_alignment) {
    size_t current_align = current_alignment;


    return current_align;
}

bool mLine::isKeyDefined() {
    return false;
}

void mLine::serializeKey(eprosima::fastcdr::Cdr &scdr) const {
    (void) scdr;


}
