// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file BigData.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _BIGDATA_H_
#define _BIGDATA_H_

// TODO Poner en el contexto.

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif
#else
#define eProsima_user_DllExport
#endif

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(BigData_SOURCE)
#define BigData_DllAPI __declspec( dllexport )
#else
#define BigData_DllAPI __declspec( dllimport )
#endif // BigData_SOURCE
#else
#define BigData_DllAPI
#endif
#else
#define BigData_DllAPI
#endif // _WIN32

namespace eprosima {
    namespace fastcdr {
        class Cdr;
    }
}

/*!
 * @brief This class represents the structure BigData defined by the user in the IDL file.
 * @ingroup BIGDATA
 */
class BigData {
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport BigData();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~BigData();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object BigData that will be copied.
     */
    eProsima_user_DllExport BigData(const BigData &x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object BigData that will be copied.
     */
    eProsima_user_DllExport BigData(BigData &&x);

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object BigData that will be copied.
     */
    eProsima_user_DllExport BigData &operator=(const BigData &x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object BigData that will be copied.
     */
    eProsima_user_DllExport BigData &operator=(BigData &&x);

    /*!
     * @brief This function sets a value in member id
     * @param _id New value for member id
     */
    inline eProsima_user_DllExport void id(uint8_t _id) {
        m_id = _id;
    }

    /*!
     * @brief This function returns the value of member id
     * @return Value of member id
     */
    inline eProsima_user_DllExport uint8_t id() const {
        return m_id;
    }

    /*!
     * @brief This function returns a reference to member id
     * @return Reference to member id
     */
    inline eProsima_user_DllExport uint8_t &id() {
        return m_id;
    }

    /*!
     * @brief This function copies the value in member array
     * @param _array New value to be copied in member array
     */
    inline eProsima_user_DllExport void array(const std::array<char, 500000> &_array) {
        m_array = _array;
    }

    /*!
     * @brief This function moves the value in member array
     * @param _array New value to be moved in member array
     */
    inline eProsima_user_DllExport void array(std::array<char, 500000> &&_array) {
        m_array = std::move(_array);
    }

    /*!
     * @brief This function returns a constant reference to member array
     * @return Constant reference to member array
     */
    inline eProsima_user_DllExport const std::array<char, 500000> &array() const {
        return m_array;
    }

    /*!
     * @brief This function returns a reference to member array
     * @return Reference to member array
     */
    inline eProsima_user_DllExport std::array<char, 500000> &array() {
        return m_array;
    }

    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(const BigData &data, size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(eprosima::fastcdr::Cdr &cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(eprosima::fastcdr::Cdr &cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(eprosima::fastcdr::Cdr &cdr) const;

private:
    uint8_t m_id;
    std::array<char, 500000> m_array;
};

#endif // _BIGDATA_H_