// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file InfoPubSubMain.cpp
 * This file acts as a main entry point to the application.
 *
 * This file was generated by the tool fastcdrgen.
 */

#include <thread>

#include "InfoPublisher.h"
#include "InfoSubscriber.h"


#include <fastrtps/Domain.h>

using namespace eprosima;
using namespace eprosima::fastrtps;

int main(int argc, char **argv) {
    std::cout << "Starting " << std::endl;
    InfoPublisher mypub;
    InfoSubscriber mysub;
    if (mypub.init() && mysub.init()) {
        std::thread pub_thread(&InfoPublisher::run, &mypub);
        std::thread sub_thread(&InfoSubscriber::run, &mysub);

        pub_thread.detach();
        sub_thread.detach();
    }
    while (1) {}

    return 0;
}
