// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file FlowControl.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace { char dummy; }
#endif

#include "FlowControl.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>

using namespace eprosima::fastcdr::exception;

#include <utility>

FlowControl::FlowControl() {
    m_id = 0;

    memset(&m_array, 0, (500000) * 1);

}

FlowControl::~FlowControl() {
}

FlowControl::FlowControl(const FlowControl &x) {
    m_id = x.m_id;
    m_array = x.m_array;
}

FlowControl::FlowControl(FlowControl &&x) {
    m_id = x.m_id;
    m_array = std::move(x.m_array);
}

FlowControl &FlowControl::operator=(const FlowControl &x) {
    m_id = x.m_id;
    m_array = x.m_array;

    return *this;
}

FlowControl &FlowControl::operator=(FlowControl &&x) {
    m_id = x.m_id;
    m_array = std::move(x.m_array);

    return *this;
}

size_t FlowControl::getMaxCdrSerializedSize(size_t current_alignment) {
    size_t initial_alignment = current_alignment;

    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    current_alignment += ((500000) * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    return current_alignment - initial_alignment;
}

size_t FlowControl::getCdrSerializedSize(const FlowControl &data, size_t current_alignment) {
    (void) data;
    size_t initial_alignment = current_alignment;

    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    current_alignment += ((500000) * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    return current_alignment - initial_alignment;
}

void FlowControl::serialize(eprosima::fastcdr::Cdr &scdr) const {
    scdr << m_id;
    scdr << m_array;
}

void FlowControl::deserialize(eprosima::fastcdr::Cdr &dcdr) {
    dcdr >> m_id;
    dcdr >> m_array;
}

size_t FlowControl::getKeyMaxCdrSerializedSize(size_t current_alignment) {
    size_t current_align = current_alignment;


    return current_align;
}

bool FlowControl::isKeyDefined() {
    return false;
}

void FlowControl::serializeKey(eprosima::fastcdr::Cdr &scdr) const {
    (void) scdr;


}